from __future__ import annotations

PAGE = r'''<!doctype html>
<html lang="ru">
<head>
<meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>Book Reader AI</title>
<style>
:root{font-family:Inter,ui-sans-serif,system-ui,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif;color:#171717;background:#f5f5f4}
*{box-sizing:border-box}body{margin:0;padding:24px}.shell{width:min(1100px,100%);margin:auto;display:grid;gap:20px}.card{background:#fff;border:1px solid #e7e5e4;border-radius:24px;padding:28px;box-shadow:0 16px 50px rgba(0,0,0,.05)}h1{font-size:clamp(30px,6vw,52px);line-height:1;margin:0 0 12px;letter-spacing:-.04em}.lead{color:#57534e;font-size:17px;line-height:1.55;margin:0 0 24px}.drop{display:block;border:1.5px dashed #a8a29e;border-radius:18px;padding:28px 18px;text-align:center;cursor:pointer;background:#fafaf9}.drop strong{display:block;font-size:18px;margin-bottom:7px}.drop span,.tiny{color:#78716c;font-size:13px;line-height:1.5}input[type=file]{display:none}.row{display:grid;grid-template-columns:1fr auto;gap:12px;margin-top:16px}select,button{height:46px;border-radius:13px;border:1px solid #d6d3d1;background:white;padding:0 14px;font:inherit}button{background:#171717;color:#fff;border-color:#171717;font-weight:650;cursor:pointer;padding:0 22px}button:disabled{opacity:.45}.status{display:none;margin-top:20px}.status.on{display:block}.meta{display:flex;justify-content:space-between;gap:12px;font-size:14px;color:#57534e;margin-bottom:8px}.bar{height:9px;border-radius:999px;background:#e7e5e4;overflow:hidden}.bar>i{display:block;height:100%;width:0;background:#171717;transition:width .3s}.links{display:flex;gap:16px;flex-wrap:wrap;margin-top:14px}.links a{display:none;color:#171717;font-weight:700;text-decoration:none}.links a.on{display:inline}.error{color:#b91c1c;margin-top:10px;font-size:14px}.reader{display:none}.reader.on{display:block}.reader-head{position:sticky;top:12px;z-index:2;background:rgba(255,255,255,.94);backdrop-filter:blur(10px);padding:10px 0 16px;border-bottom:1px solid #eee}.book{max-width:760px;margin:20px auto 0;font-family:Georgia,"Times New Roman",serif;font-size:19px;line-height:1.72}.book p{margin:0 0 1em;transition:background .5s}.book p.translated{background:linear-gradient(90deg,rgba(34,197,94,.09),transparent);border-radius:4px}.chapter{font-family:Inter,ui-sans-serif,system-ui;font-weight:700;font-size:14px;color:#78716c;margin:34px 0 12px;text-transform:uppercase;letter-spacing:.08em}@media(max-width:620px){body{padding:12px}.card{padding:20px}.row{grid-template-columns:1fr}.book{font-size:18px}}
</style>
</head><body><main class="shell">
<section class="card"><h1>Book Reader AI</h1><p class="lead">Прогрессивный литературный перевод: GigaChat-3-Lightning переводит текст по кусочкам, а DeepSeek V4.1 Flash анализирует произведение, стиль и сложные места. Читать можно сразу — готовые абзацы заменяют английский прямо в открытой книге.</p>
<label class="drop" id="drop"><input id="file" type="file" accept=".fb2,.epub,.txt,.docx"><strong id="fileLabel">Перетащите книгу сюда или выберите файл</strong><span>FB2 · EPUB · TXT · DOCX</span></label>
<div class="row"><select id="mode"><option value="optimal">Optimal — прогрессивный перевод + выборочная редактура</option><option value="literary">Literary — больше внимания сложным местам</option><option value="fast">Fast — только базовый перевод</option></select><button id="go" disabled>Начать перевод</button></div>
<section class="status" id="status"><div class="meta"><span id="phase">Подготовка…</span><span id="percent">0%</span></div><div class="bar"><i id="bar"></i></div><div id="details" class="tiny"></div><div id="error" class="error"></div><div class="links"><a id="partial">Скачать текущую версию</a><a id="download">Скачать готовую книгу</a></div></section>
<p class="tiny">Основной перевод: GigaChat-3-Lightning. Анализ книги, Style Card, контекст, hard cases и выборочная литературная правка: DeepSeek V4.1 Flash. V4 Pro не используется.</p></section>
<section class="card reader" id="reader"><div class="reader-head"><b>Живой ридер</b><div id="readerMeta" class="tiny">Загружаю текст…</div></div><article class="book" id="book"></article></section>
</main>
<script>
const file=document.querySelector('#file'),drop=document.querySelector('#drop'),label=document.querySelector('#fileLabel'),go=document.querySelector('#go'),mode=document.querySelector('#mode'),status=document.querySelector('#status'),phase=document.querySelector('#phase'),percent=document.querySelector('#percent'),bar=document.querySelector('#bar'),details=document.querySelector('#details'),err=document.querySelector('#error'),download=document.querySelector('#download'),partial=document.querySelector('#partial'),reader=document.querySelector('#reader'),book=document.querySelector('#book'),readerMeta=document.querySelector('#readerMeta');
let revision=0,currentJob=null,totalSegments=0,translatedCount=0;
function chosen(f){if(!f)return;label.textContent=f.name;go.disabled=false}file.onchange=()=>chosen(file.files[0]);['dragenter','dragover'].forEach(e=>drop.addEventListener(e,x=>x.preventDefault()));drop.addEventListener('drop',e=>{e.preventDefault();if(e.dataTransfer.files.length){file.files=e.dataTransfer.files;chosen(file.files[0])}});
const phases={queued:'В очереди',parsing:'Разбираю книгу',analyzing_book:'Анализирую произведение',chapter_brief:'Анализирую главу',chapter_translate:'Перевожу',translating:'Перевожу',chapter_polish:'Литературная правка',chapter_gate:'Проверяю качество',done:'Готово',error:'Ошибка'};
async function loadReader(id){const r=await fetch('/jobs/'+id+'/reader');if(!r.ok)return;const j=await r.json();reader.classList.add('on');book.innerHTML='';let last='';totalSegments=j.segments.length;for(const s of j.segments){if(s.chapter&&s.chapter!==last){const h=document.createElement('div');h.className='chapter';h.textContent=s.chapter;book.appendChild(h);last=s.chapter}const p=document.createElement('p');p.dataset.sid=s.id;p.textContent=s.text;book.appendChild(p)}readerMeta.textContent=`0 из ${totalSegments} фрагментов переведено`}
function applyDelta(data){for(const [sid,text] of Object.entries(data.segments||{})){const p=book.querySelector(`[data-sid="${sid}"]`);if(p){p.textContent=text;p.classList.add('translated')}}revision=data.revision||revision;translatedCount=data.ready_segments||translatedCount;readerMeta.textContent=`${translatedCount} из ${totalSegments} фрагментов переведено · книга продолжает переводиться в фоне`}
async function pollSegments(id){if(id!==currentJob)return;try{const r=await fetch(`/jobs/${id}/segments?after=${revision}`);if(r.ok)applyDelta(await r.json())}catch(e){}setTimeout(()=>pollSegments(id),900)}
async function poll(id){if(id!==currentJob)return;const r=await fetch('/jobs/'+id),j=await r.json();phase.textContent=phases[j.phase||j.status]||j.phase||j.status;const p=j.progress||0;percent.textContent=p+'%';bar.style.width=p+'%';let bits=[];if(Number.isInteger(j.ready_segments))bits.push('Готово фрагментов: '+j.ready_segments);if(j.chapter)bits.push('Глава: '+j.chapter);if(j.translator)bits.push('Переводчик: '+j.translator);details.textContent=bits.join(' · ');if(j.partial_ready){partial.href='/jobs/'+id+'/partial-download';partial.classList.add('on')}if(j.status==='done'){go.disabled=false;download.href='/jobs/'+id+'/download';download.classList.add('on');readerMeta.textContent=`Готово: ${translatedCount||totalSegments} из ${totalSegments} фрагментов`;return}if(j.status==='error'){go.disabled=false;err.textContent=(j.error||'Ошибка')+' Уже переведённые абзацы остаются доступными.';return}setTimeout(()=>poll(id),900)}
go.onclick=async()=>{err.textContent='';download.classList.remove('on');partial.classList.remove('on');status.classList.add('on');go.disabled=true;revision=0;translatedCount=0;const data=new FormData();data.append('file',file.files[0]);data.append('mode',mode.value);const r=await fetch('/books',{method:'POST',body:data});const j=await r.json();if(!r.ok){go.disabled=false;err.textContent=j.detail||'Ошибка загрузки';return}currentJob=j.job_id;await loadReader(currentJob);poll(currentJob);pollSegments(currentJob)};
</script></body></html>'''
