from __future__ import annotations

PAGE = r'''<!doctype html>
<html lang="ru">
<head>
<meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>Book Reader AI</title>
<style>
:root{font-family:Inter,ui-sans-serif,system-ui,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif;color:#171717;background:#f5f5f4}
*{box-sizing:border-box}body{margin:0;min-height:100vh;display:grid;place-items:center;padding:24px}.card{width:min(760px,100%);background:#fff;border:1px solid #e7e5e4;border-radius:28px;padding:32px;box-shadow:0 18px 60px rgba(0,0,0,.07)}
h1{font-size:clamp(30px,6vw,52px);line-height:1;margin:0 0 12px;letter-spacing:-.04em}.lead{color:#57534e;font-size:17px;line-height:1.55;margin:0 0 28px}.drop{display:block;border:1.5px dashed #a8a29e;border-radius:20px;padding:34px 20px;text-align:center;cursor:pointer;background:#fafaf9}.drop:hover{background:#f5f5f4}.drop strong{display:block;font-size:18px;margin-bottom:7px}.drop span{color:#78716c;font-size:14px}input[type=file]{display:none}.row{display:grid;grid-template-columns:1fr auto;gap:14px;margin-top:18px}select,button{height:48px;border-radius:14px;border:1px solid #d6d3d1;background:white;padding:0 14px;font:inherit}button{background:#171717;color:#fff;border-color:#171717;font-weight:650;cursor:pointer;padding:0 24px}button:disabled{opacity:.45;cursor:not-allowed}.status{display:none;margin-top:24px}.status.on{display:block}.meta{display:flex;justify-content:space-between;gap:12px;font-size:14px;color:#57534e;margin-bottom:9px}.bar{height:10px;border-radius:999px;background:#e7e5e4;overflow:hidden}.bar>i{display:block;height:100%;width:0;background:#171717;transition:width .3s}.download{display:none;margin-top:16px;text-decoration:none;color:#171717;font-weight:700}.download.on{display:inline-block}.error{color:#b91c1c;margin-top:12px;font-size:14px}.tiny{margin-top:20px;color:#78716c;font-size:12px;line-height:1.5}.modes{display:grid;grid-template-columns:repeat(3,1fr);gap:8px;margin-top:12px}.mode-note{padding:10px;border:1px solid #e7e5e4;border-radius:12px;font-size:12px;color:#57534e}.mode-note b{display:block;color:#171717;margin-bottom:3px}@media(max-width:620px){.row{grid-template-columns:1fr}.modes{grid-template-columns:1fr}}
</style>
</head><body><main class="card"><h1>Book Reader AI</h1><p class="lead">Каскадный литературный перевод: дешёвая модель переводит весь текст, quality gate находит сложные места, а Qwen3.8 Flash редактирует только их.</p>
<label class="drop" id="drop"><input id="file" type="file" accept=".fb2,.epub,.txt,.docx"><strong id="fileLabel">Перетащите книгу сюда или выберите файл</strong><span>FB2 · EPUB · TXT · DOCX</span></label>
<div class="row"><select id="mode"><option value="optimal">Optimal — выборочная редактура</option><option value="literary">Literary — + сильная модель для hard cases</option><option value="fast">Fast — только базовый перевод</option></select><button id="go" disabled>Перевести</button></div>
<div class="modes"><div class="mode-note"><b>Fast</b>Только базовый перевод.</div><div class="mode-note"><b>Optimal</b>Gate → Qwen3.8 Flash только для отмеченных фрагментов.</div><div class="mode-note"><b>Literary</b>Hard cases дополнительно получает senior-модель.</div></div>
<section class="status" id="status"><div class="meta"><span id="phase">Подготовка…</span><span id="percent">0%</span></div><div class="bar"><i id="bar"></i></div><div id="details" class="tiny"></div><div id="error" class="error"></div><a id="download" class="download">Скачать перевод →</a></section>
<p class="tiny">По умолчанию: DeepSeek V4 Flash — перевод/gate/память, Qwen3.8 Flash — выборочная литературная редактура, DeepSeek V4 Pro — только сложные места в Literary. Можно переключить базовый перевод на локальный MADLAD-400-3B.</p></main>
<script>
const file=document.querySelector('#file'),drop=document.querySelector('#drop'),label=document.querySelector('#fileLabel'),go=document.querySelector('#go'),mode=document.querySelector('#mode'),status=document.querySelector('#status'),phase=document.querySelector('#phase'),percent=document.querySelector('#percent'),bar=document.querySelector('#bar'),details=document.querySelector('#details'),err=document.querySelector('#error'),download=document.querySelector('#download');
function chosen(f){if(!f)return;label.textContent=f.name;go.disabled=false}file.onchange=()=>chosen(file.files[0]);['dragenter','dragover'].forEach(e=>drop.addEventListener(e,x=>{x.preventDefault();drop.style.background='#f5f5f4'}));['dragleave','drop'].forEach(e=>drop.addEventListener(e,x=>{x.preventDefault();drop.style.background=''}));drop.addEventListener('drop',e=>{if(e.dataTransfer.files.length){file.files=e.dataTransfer.files;chosen(file.files[0])}});
const phases={queued:'В очереди',parsing:'Разбираю книгу',analyzing_style:'Создаю style bible',translating:'Базовый перевод',quality_gate:'Проверяю качество',selective_edit:'Редактирую сложные места',hard_cases:'Разбираю сложные случаи',updating_memory:'Обновляю память книги',building_book:'Собираю файл',done:'Готово',error:'Ошибка'};
async function poll(id){const r=await fetch('/jobs/'+id),j=await r.json();phase.textContent=phases[j.phase||j.status]||j.phase||j.status;const p=j.progress||0;percent.textContent=p+'%';bar.style.width=p+'%';let bits=[];if(j.chapter)bits.push('Глава: '+j.chapter);if(Number.isInteger(j.flagged))bits.push('На редактуру: '+j.flagged);if(j.translator)bits.push('Переводчик: '+j.translator);details.textContent=bits.join(' · ');if(j.status==='done'){go.disabled=false;download.href='/jobs/'+id+'/download';download.classList.add('on');if(j.usage?.total)details.textContent=`API: ${j.usage.total.requests||0} запросов · ${j.usage.total.total_tokens||0} токенов`;return}if(j.status==='error'){go.disabled=false;err.textContent=j.error||'Неизвестная ошибка';return}setTimeout(()=>poll(id),900)}
go.onclick=async()=>{err.textContent='';download.classList.remove('on');status.classList.add('on');go.disabled=true;const data=new FormData();data.append('file',file.files[0]);data.append('mode',mode.value);const r=await fetch('/books',{method:'POST',body:data});const j=await r.json();if(!r.ok){go.disabled=false;err.textContent=j.detail||'Ошибка загрузки';return}poll(j.job_id)};
</script></body></html>'''
